/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha5 "github.com/aws/karpenter/pkg/apis/provisioning/v1alpha5"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvisioners implements ProvisionerInterface
type FakeProvisioners struct {
	Fake *FakeKarpenterV1alpha5
}

var provisionersResource = schema.GroupVersionResource{Group: "karpenter.sh", Version: "v1alpha5", Resource: "provisioners"}

var provisionersKind = schema.GroupVersionKind{Group: "karpenter.sh", Version: "v1alpha5", Kind: "Provisioner"}

// Get takes name of the provisioner, and returns the corresponding provisioner object, and an error if there is any.
func (c *FakeProvisioners) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha5.Provisioner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(provisionersResource, name), &v1alpha5.Provisioner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha5.Provisioner), err
}

// List takes label and field selectors, and returns the list of Provisioners that match those selectors.
func (c *FakeProvisioners) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha5.ProvisionerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(provisionersResource, provisionersKind, opts), &v1alpha5.ProvisionerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha5.ProvisionerList{ListMeta: obj.(*v1alpha5.ProvisionerList).ListMeta}
	for _, item := range obj.(*v1alpha5.ProvisionerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested provisioners.
func (c *FakeProvisioners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(provisionersResource, opts))
}

// Create takes the representation of a provisioner and creates it.  Returns the server's representation of the provisioner, and an error, if there is any.
func (c *FakeProvisioners) Create(ctx context.Context, provisioner *v1alpha5.Provisioner, opts v1.CreateOptions) (result *v1alpha5.Provisioner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(provisionersResource, provisioner), &v1alpha5.Provisioner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha5.Provisioner), err
}

// Update takes the representation of a provisioner and updates it. Returns the server's representation of the provisioner, and an error, if there is any.
func (c *FakeProvisioners) Update(ctx context.Context, provisioner *v1alpha5.Provisioner, opts v1.UpdateOptions) (result *v1alpha5.Provisioner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(provisionersResource, provisioner), &v1alpha5.Provisioner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha5.Provisioner), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvisioners) UpdateStatus(ctx context.Context, provisioner *v1alpha5.Provisioner, opts v1.UpdateOptions) (*v1alpha5.Provisioner, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(provisionersResource, "status", provisioner), &v1alpha5.Provisioner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha5.Provisioner), err
}

// Delete takes name of the provisioner and deletes it. Returns an error if one occurs.
func (c *FakeProvisioners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(provisionersResource, name), &v1alpha5.Provisioner{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvisioners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(provisionersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha5.ProvisionerList{})
	return err
}

// Patch applies the patch and returns the patched provisioner.
func (c *FakeProvisioners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha5.Provisioner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(provisionersResource, name, pt, data, subresources...), &v1alpha5.Provisioner{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha5.Provisioner), err
}
