/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha5

import (
	v1alpha5 "github.com/aws/karpenter/pkg/apis/provisioning/v1alpha5"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProvisionerLister helps list Provisioners.
// All objects returned here must be treated as read-only.
type ProvisionerLister interface {
	// List lists all Provisioners in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha5.Provisioner, err error)
	// Get retrieves the Provisioner from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha5.Provisioner, error)
	ProvisionerListerExpansion
}

// provisionerLister implements the ProvisionerLister interface.
type provisionerLister struct {
	indexer cache.Indexer
}

// NewProvisionerLister returns a new ProvisionerLister.
func NewProvisionerLister(indexer cache.Indexer) ProvisionerLister {
	return &provisionerLister{indexer: indexer}
}

// List lists all Provisioners in the indexer.
func (s *provisionerLister) List(selector labels.Selector) (ret []*v1alpha5.Provisioner, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha5.Provisioner))
	})
	return ret, err
}

// Get retrieves the Provisioner from the index for a given name.
func (s *provisionerLister) Get(name string) (*v1alpha5.Provisioner, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha5.Resource("provisioner"), name)
	}
	return obj.(*v1alpha5.Provisioner), nil
}
