name: CI-TEST
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.22.x", "1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make ci-test
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
