name: Deflake
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  deflake:
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: ./.github/actions/install-deps
      - name: Running tests 5 times to find flaky tests
        id: run-deflake
        run: make deflake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: always()
        name: Post commit status
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"${{ steps.run-deflake.outcome }}","target_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","context":"Deflake Tests (cron)"}'
