name: DryRunGenPR
on:
  pull_request:
  workflow_dispatch:
jobs:
  dryrun-gen:
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - run: make prepare-website
        env:
          GIT_TAG: v0.10000.0 # Mock version for testing website generation
